# Conceptos básicos de R
## Introducción
__R es un entorno de programación creado específicamente para estadística.__ Es un lenguaje de __scripting__. R puede usarse de forma interactiva (como veremos en este cuaderno) o puede ejecutarse una lista de comandos almacenados en un archivo de texto plano (llamado «script»).

Desde el Jupyter Notebook, podemos acceder al kernel de R (el programa que interpreta el código R y devuelve los resultados). Esta es solo una forma de usar R. También aprenderemos a usar un programa llamado __Rstudio__.

Como pueden ver, el notebook se basa en el navegador (abre una ventana en su navegador) y funciona de forma muy similar a un servidor web. Este notebook ejecuta un kernel R, pero podríamos elegir un kernel Python, un kernel bash (shell de Unix) o alguno de una larga lista que actualmente está en expansión.

El cuaderno se compone de celdas. Las celdas pueden ser de __Código o de Markdown__. El __código__ sirve para escribir comandos de R. __Markdown__ sirve para texto y es un lenguaje de marcas (parecido al HTML). Esta celda es de Markdown.

Más información sobre Markdown aquí:  
[https://tutorialmarkdown.com/sintaxis](https://tutorialmarkdown.com/sintaxis)

Las celdas de código requieren sintaxis R. La siguiente celda es una celda R:

In [1]:
# Esta es una celda R. El '#' le dice a R que este es un comentario 
3+1

[1] 4

Al ejecutar la celda de código, se ejecuta el código R (3+1) y se devuelve la salida en una celda de salida. Para ejecutar una celda de código, puede presionar Mayús+Intro o el botón de ejecución en la parte superior de la pantalla.

## Tipos de datos
En cualquier lenguaje de programación, existen los conceptos de "tipos de datos" y "estructuras de datos". Esto se debe a que los programas manipulan datos, y cada tipo de datos requiere una manipulación diferente. Por ejemplo, los números se tratan de forma diferente a los caracteres (o cadenas de caracteres), y los números individuales se tratan de forma diferente a las listas de números (vectores) o matrices de números (arrays).

Los siguientes son algunos tipos de datos R simples:
* numeric
* character
* logical (TRUE o FALSE)
* complex    

Los tipos de datos básicos se pueden combinar para formar estructuras de datos:
* Vector
* Matrix
* String
* Data frame

Ejemplos:

In [1]:
class(c(1,3,2,8.4)) #This is a vector

class(matrix(c(1,3,2,4,5,6),nrow=2,ncol=3)) #This is a matrix

"This is a string!"

data.frame(c("This is a string","This is another string"),matrix(c(1:6),nrow=2,ncol=3))

[1] "numeric"

[1] "matrix" "array"

[1] "This is a string!"

  c..This.is.a.string....This.is.another.string.. X1 X2 X3
1 This is a string                                1  3  5
2 This is another string                          2  4  6

Algo importante a señalar es que los Data frames pueden combinar distintos tipos de datos.

## Creación de Objetos
### c - Concatenate
Acabamos de ver este comando en acción. El comando 'c' combina objetos por concatenación.
Este ejemplo crea un vector con 3 valores.

In [3]:
c ( 5 , 6 , 7 )

[1] 5 6 7

Podemos añadir más valores al vector usando c (concatenar) resultando otro vector con más valores

In [4]:
c(c(5,6,7),8,9)

[1] 5 6 7 8 9

Normalmente asignaremos los vectores con alguna variable con nombre. Por lo que generalmente usaremos un código más parecido a este:

In [5]:
v1<-c(5,6,7)
v2<-c(v1,8,9)
print(v1)
print(v2)

[1] 5 6 7
[1] 5 6 7 8 9

### rbind
Si quisiéramos crear una matriz, podríamos usar el comando `matrix` como se indica arriba

In [6]:
matrix(c(1,3,2,4,5,6),nrow=2,ncol=3)

     [,1] [,2] [,3]
[1,] 1    2    5
[2,] 3    4    6

O podemos crear vectores y combinarlos con `rbind` (rbind viene de "row bind" "enlace de filas")

In [7]:
v1<-c(1,2,5)
v2<-c(3,4,6)
m1<-rbind(v1,v2)
m1
class(m1)

   [,1] [,2] [,3]
v1 1    2    5
v2 3    4    6

[1] "matrix" "array"

Observe que R asigna automáticamente nombres a las filas (v1 y v2).

sigue por aquí: https://people.duke.edu/~ccc14/ngs-2015/BasicRinJupyterAndRstudio.html?utm_source=chatgpt.com

### cbind
También tenemos cbind que viene column bind (enlace de columnas) y que nos puede servir para crear matrices o ampliarlas, como es el caso del siguiente ejemplo:

In [4]:
m1<-matrix(c(1,2,3,4),nrow=2,ncol=2)
m1

     [,1] [,2]
[1,] 1    3
[2,] 2    4

In [5]:
m2<-cbind(m1,c(5,6))
m2

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

## Como Acceder a la Documentación de R
Aunque la mejor forma de aprender es programando, por eso les pondré unos cuadernos de ejercicios para que puedan practicar/jugar con los comandos de R.
Podemos usar Google para encontrar la documentación sobre R, aunque el propio R dispone de algunas funciones que pueden seernos útiles para programar:
* __`?`:__ Si conoce el nombre del comando que del que desea conocer su uso, puede simplemente escribir `?nombre_del_comando` en una celda de código y ejecutarlo. Por ejemplo, para saber el uso del comando help pondríamos `?help`.
* __`help()`:__ Pasaremos como parámetro la función de la que queremos leer su documentción. Es similar a `?` 
* __`example()`:__ Muestra ejemplo de uso de la función que pasaremos por parámetro. Por ejemplo para ver ejemplos de uso de `sep` pondríamos: `example(seq)`
* __`apropos()`:__ Nos sirve para buscar funciones que contiene la cadena pasada por parámetro. Por ejemplo àpropos("seq") devuelve toas las funciones que contienen la cadena "seq"
* __`??`:__ Para una búsqueda más amplia utilizando coincidencias “difusas”, utilice ??“precedido” al término de búsqueda. Por ejemplo `??seq`

In [ ]:
?help

In [ ]:
help(seq)

In [ ]:
example(seq)

In [ ]:
apropos("seq")

In [ ]:
??seq